// Sockets
const SERVER_LEAVE = "SERVER_LEAVE";
const SERVER_JOIN = "SERVER_JOIN";
const CHANNEL_MESSAGE = "CHANNEL_MESSAGE";
const MEMBER_JOIN = "MEMBER_JOIN";
const MEMBER_LEAVE = "MEMBER_LEAVE";

module.exports = {
  SERVER_LEAVE,
  SERVER_JOIN,
  CHANNEL_MESSAGE,
  MEMBER_JOIN,
  MEMBER_LEAVE,
};
