// Sockets
const SERVER_LEAVE = "SERVER_LEAVE";
const SERVER_JOIN = "SERVER_JOIN";
const CHANNEL_MESSAGE = "CHANNEL_MESSAGE";
const MEMBER_UPDATE = "MEMBER_UPDATE";
const MEMBER_KICK = "MEMBER_KICK";
const SERVER_EDIT = "SERVER_EDIT";
const SERVERS_UPDATE = "SERVERS_UPDATE";
const CHANNEL_EDIT = "CHANNEL_EDIT";
const CHANNEL_NEW = "CHANNEL_NEW";
const CHANNEL_DELETE = "CHANNEL_DELETE";

module.exports = {
  SERVER_LEAVE,
  SERVER_JOIN,
  CHANNEL_MESSAGE,
  MEMBER_UPDATE,
  MEMBER_KICK,
  SERVER_EDIT,
  SERVERS_UPDATE,
  CHANNEL_DELETE,
  CHANNEL_NEW,
  CHANNEL_EDIT,
};
