// Sockets
const SERVER_LEAVE = "SERVER_LEAVE";
const SERVER_JOIN = "SERVER_JOIN";
const CHANNEL_MESSAGE = "CHANNEL_MESSAGE";
const MEMBER_UPDATE = "MEMBER_UPDATE";
const MEMBER_KICK = "MEMBER_KICK";

module.exports = {
  SERVER_LEAVE,
  SERVER_JOIN,
  CHANNEL_MESSAGE,
  MEMBER_UPDATE,
  MEMBER_KICK,
};
