export const dms = [
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
  {
    id: 1,

    user: {
      id: 1,
      full_name: "HyunSu Kim",
      img: "/images/avatar2.jpg",
      is_active: true,
      username: "Learth",
      bio: "Hi, we are disnode!",
    },
  },
  {
    id: 2,
    user: {
      id: 2,
      full_name: "Jonathan Su",
      img: "/images/avatar.jpg",
      is_active: true,
      username: "smart lad",
      bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
    },
  },
  {
    id: 3,
    user: {
      id: 3,
      full_name: "Adam Hirzalla",
      img: "/images/avatar3.jpg",
      is_active: true,
    },
  },
];

export const messages = [
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 1,
    sender_nickname: "smart lad",
    sender_avatar: "/images/avatar.jpg",
    sender_id: 2,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 2,
    sender_nickname: "Hyunsu",
    sender_avatar: "/images/avatar2.jpg",
    sender_id: 3,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 1,
    sender_nickname: "smart lad",
    sender_avatar: "/images/avatar.jpg",
    sender_id: 2,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 2,
    sender_nickname: "Hyunsu",
    sender_avatar: "/images/avatar2.jpg",
    sender_id: 3,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 1,
    sender_nickname: "smart lad",
    sender_avatar: "/images/avatar.jpg",
    sender_id: 2,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 2,
    sender_nickname: "Hyunsu",
    sender_avatar: "/images/avatar2.jpg",
    sender_id: 3,
    body: "Coming soon!!",
    sent_at: "now",
  },
  {
    id: 3,
    sender_nickname: "Learth",
    sender_avatar: "/images/avatar3.jpg",
    sender_id: 1,
    body: "Coming soon!!",
    sent_at: "now",
  },
];

export const friends = [
  {
    id: 8,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: true,
    username: "Learth",
    bio: "Hi, we are disnode!",
  },
  {
    id: 9,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: true,
    username: "smart lad",
    bio: "Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! Hi, we are disnode! ",
  },
  {
    id: 1,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: true,
  },
  {
    id: 2,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: true,
  },
  {
    id: 3,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: true,
  },
  {
    id: 4,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
  {
    id: 5,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: false,
  },
  {
    id: 6,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: false,
  },
  {
    id: 7,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
  {
    id: 2,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: true,
  },
  {
    id: 3,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: true,
  },
  {
    id: 4,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
  {
    id: 5,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: false,
  },
  {
    id: 6,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: false,
  },
  {
    id: 7,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
  {
    id: 2,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: true,
  },
  {
    id: 3,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: true,
  },
  {
    id: 4,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
  {
    id: 5,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: false,
  },
  {
    id: 6,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: false,
  },
  {
    id: 7,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
  {
    id: 2,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: true,
  },
  {
    id: 3,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: true,
  },
  {
    id: 4,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
  {
    id: 5,
    full_name: "HyunSu Kim",
    img: "/images/avatar2.jpg",
    is_active: false,
  },
  {
    id: 6,
    full_name: "Jonathan Su",
    img: "/images/avatar.jpg",
    is_active: false,
  },
  {
    id: 7,
    full_name: "Adam Hirzalla",
    img: "/images/avatar3.jpg",
    is_active: false,
  },
];
