### Test Route
GET http://localhost:8001/api/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVhdmFuNTU1IiwiaWF0IjoxNjQwODEyMjUwLCJleHAiOjE2NDA4MTIyNjB9.fdEDJUQZa4a_ww_CWKmqXxA5KI1LQR0SIarar5o9F9I

### Register Route
POST http://localhost:8001/api/register
Content-Type: application/json

{ "full_name": "Ted Mosby", "display_name": "Tedy", "username": "ted555", "email": "ted.mosby@gmail.com", "password": "password" }

### Login Route
POST http://localhost:8001/api/login
Content-Type: application/json

{ "username": "eavan555", "password":"password" }