### All users
GET http://localhost:8001/api/users

### Test token
GET  http://localhost:8001/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQxMDEwMzIzLCJleHAiOjE2NDEwNDYzMjN9.3YHRSDOr_QfhfijbKus6zTAhLtvK3cR5EFkSplOAcoc

### Test refresh token
GET http://localhost:8001/api/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjQxMDEwMjQ1LCJleHAiOjE2NDEwOTY2NDV9.sOeXWoxpb5QmbaPii_ZLiiY_34ercZhPVNqj36_cc40

### Register Route
POST http://localhost:8001/api/register
Content-Type: application/json

{ "full_name": "Ted Mosby", "display_name": "Tedy", "username": "ted555", "email": "ted.mosby@gmail.com", "password": "password", "repeat_password": "password" }

### Login Route
POST http://localhost:8001/api/login
Content-Type: application/json

{ "username": "hjonsu555", "password": "password"}

### Reset DB
GET http://localhost:8001/api/debug/reset_db