### Reset DB
GET http://localhost:8001/api/debug/reset_db


### create a channel
POST http://localhost:8001/api/servers/1/channels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyMzg2MDIzLCJleHAiOjE2NDI0NzI0MjN9.LB7TkLU3L2QaCZpTqRMhE2XA6qUqTsl1vSbneyFPpU4
Content-Type: application/json

{ "title": "test channel" }