### Reset DB
GET http://localhost:8001/api/debug/reset_db


### create a channel
POST http://localhost:8001/api/servers/3/channels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyNTg3MTYyLCJleHAiOjE2NDI2NzM1NjJ9.WSeFt8npPl7FLFnRYa2wGy9K81R_wyFeo2cw6ufsEmg
Content-Type: application/json

{ "title": "Test channel" }

### get channels for a server
POST http://localhost:8001/api/channels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyMzg2MDIzLCJleHAiOjE2NDI0NzI0MjN9.LB7TkLU3L2QaCZpTqRMhE2XA6qUqTsl1vSbneyFPpU4
Content-Type: application/json

{ "serverId": 1 }