### Reset DB
GET http://localhost:8001/api/debug/reset_db



### all servers
GET http://localhost:8001/api/servers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyNTg3MTYyLCJleHAiOjE2NDI2NzM1NjJ9.WSeFt8npPl7FLFnRYa2wGy9K81R_wyFeo2cw6ufsEmg

### querying servers (title)
GET http://localhost:8001/api/servers?title=a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyNTg3MTYyLCJleHAiOjE2NDI2NzM1NjJ9.WSeFt8npPl7FLFnRYa2wGy9K81R_wyFeo2cw6ufsEmg

### querying servers (code)
GET http://localhost:8001/api/servers?invite_code=87286749-20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyNTg3MTYyLCJleHAiOjE2NDI2NzM1NjJ9.WSeFt8npPl7FLFnRYa2wGy9K81R_wyFeo2cw6ufsEmg

### single server
POST http://localhost:8001/api/servers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyNjc1NTY5LCJleHAiOjE2NDI3NjE5Njl9.OVgQ6jc-0jt1qfBl2T8Y0FpLT955sdUadBHYUaTFgFs

### create a server
POST http://localhost:8001/api/servers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQyNDk1ODE5LCJleHAiOjE2NDI1ODIyMTl9.BvzBYGm1WO_Hzw4kh7-qbqcQ56pttYEAQRon1dQxzWU
Content-Type: application/json

{ "title": "test server", "image": "https://i.redd.it/kzndsge5ver41.png" }

